FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY platform/package*.json ./platform/

RUN npm ci

WORKDIR /app/platform

RUN npm run db:generate && npm run build

EXPOSE 3000

CMD ["npm", "run", "-w", "@cafeos/web", "start"]
